<b>
comments:
</button> 
<br>
<ul>
<?php
foreach ($block->getComments() as $comment)
{
    echo "<li> <b> ${comment['lastname']}:</b>  <span>  ${comment['comment']} </span></li>";
}
?>
</ul>

<div data-role="custom-comment-section" data-bind="scope: 'custom_comment_section'">
    <div class="content-type" data-bind="foreach: custom_comment_section().comments">
    <div>
        <span data-bind="if: ($data.post_id== document.getElementById('id-post').value ) ">
        <span data-bind="text: $data.comment">
            </span> : Pending.....  
        </span>
        </div>
    </div>    
</div>

<script type="text/x-magento-init">
{
    "[data-role=custom-comment-section]": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
    }
}
</script>