<?php
if  ($block->customerLoged())
{
?>    

<form id="comment-form" action="">
<input name="id" hidden value="<?php echo $block->getPostId();  ?>" type="text" >
<textarea class="comment-area" placeholder="comment here"></textarea>
<button id="comment-submit" class="submit"> submit</button>
</form>

<script type="text/javascript">

require(['jquery'], function($){
$(function(){
    $(document).on('click','#comment-submit', function(e){
                    e.preventDefault()
                    comment= $('#comment-form .comment-area').val()
                    $.ajax({
                        type: "POST",
                        url: "  <?php  echo $block->getUrlAjax();  ?> ",
                        data: { comment : comment,
                        id: $("#comment-form input[name='id']").val()
                        },
                        success: function (response) {
                                alert(response)
                                $('#comment-form .comment-area').val('')
                        },
                        error : function()
                        {
                            alert('fail')
                        }
                    });

    })} )
})
</script>

<?php } else  echo "<a href='/customer/account/login/'> Login to comment </a>" ?>