<style>

.text3 {
   overflow: hidden;
   text-overflow: ellipsis;
   display: -webkit-box;
   -webkit-line-clamp: 3; /* number of lines to show */
   -webkit-box-orient: vertical;
}
</style>

<?php
foreach ($block->getPosts() as $post)
    {
?>
<h1> 
<a href="<?php  echo $post->getUrl();  ?> ">  
            <?php  echo $post->getTitle();   ?> 
</a>
 </h1>
<i>  <?php  echo $post->getCreationTime();  ?>  </i>
<br>
<div>
<div class="text3">
<?php
echo $post->getContent(); 
?>
</div>
</div>

<?php
}
?>
